on: repository_dispatch

name: Build docs

jobs:
  test-dispatch:
    steps:
      - name: Print message
        run: echo 'workflow started'

      # Add check of pharmr, build docs, commit, release
