on: workflow_dispatch

name: Build docs

jobs:
  test-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo 'workflow started'

      # Add check of pharmr, build docs, commit, release
