on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0,3"

name: Check Pharmpy development version

jobs:
  run-tests:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-2022, r: 'release'}
          - {os: macOS-12, r: 'release'}
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout pharmr
        uses: actions/checkout@v3
        with:
          path: pharmr_repo

      - uses: ./pharmr_repo/.github/actions/setup-dependencies

      - uses: ./pharmr_repo/.github/actions/setup-pharmr
        with:
          as-release: false

      - uses: ./pharmr_repo/.github/actions/check-pharmr
