on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0,3"

name: Check Pharmpy development version

jobs:
  check-pharmr:
    uses: pharmpy/pharmr/.github/workflows/main.yaml@main
    with:
      as-release: false
